
# Site variables

title: TJ Prom 2015

defaults:
    -
        values:
            layout: default

# Jekyll config

encoding: utf-8

markdown: kramdown

kramdown:
    auto_ids: true

sass:
    sass_dir: _sass
