
# Site variables

title: TJ Prom 2015

defaults:
    -
        values:
            layout: default
    -
        scope:
            type: posts
        values:
            layout: question

# Jekyll config

permalink: none

gems: [bourbon, neat]

encoding: utf-8

markdown: kramdown

kramdown:
    auto_ids: true

sass:
    sass_dir: _sass
